[serial]
port = "/dev/ttyACM0"
baudrate = 9600

[hyperparameters]
# num_classes = 4        # クラス数（例: 4クラス分類）
batch_size = 32
epochs = 5
img_size = 224
learning_rate = 0.001

[directory]
image_dir = 'image/recorded'
dataset_dir = 'dataset'    
model_dir = 'model'

[model]
classes = ["0000", "0001", "0010", "0011"]
path = "model/mobilenetv3_small_latest.pth"
# path = "model/vgg_best_model.pth"

[monitoring]
THRESHOLD = 10000  # File count threshold
CHECK_INTERVAL = 60

[gpu]
gpu_index = 1